# Generated by Django 5.1.15 on 2026-05-23 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('logo', models.CharField(blank=True, max_length=512, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'db_table': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='dsa_intelligence.topic')),
            ],
            options={
                'db_table': 'question_topics',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DSAQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('slug', models.SlugField(max_length=512, unique=True)),
                ('leetcode_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('difficulty', models.CharField(db_index=True, max_length=32)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('acceptance_rate', models.FloatField(blank=True, null=True)),
                ('topics', models.ManyToManyField(blank=True, related_name='questions', to='dsa_intelligence.topic')),
            ],
            options={
                'db_table': 'dsa_questions',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='QuestionCompanyFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_bucket', models.CharField(choices=[('30_days', 'Thirty Days'), ('3_months', 'Three Months'), ('6_months', 'Six Months'), ('more_than_6_months', 'More Than Six Months'), ('all', 'All')], db_index=True, max_length=32)),
                ('frequency_percentage', models.FloatField(blank=True, null=True)),
                ('source_repo', models.CharField(max_length=128)),
                ('ingestion_timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_seen_date', models.DateField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_frequencies', to='dsa_intelligence.company')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_frequencies', to='dsa_intelligence.dsaquestion')),
            ],
            options={
                'db_table': 'question_company_frequency',
                'indexes': [models.Index(fields=['company', 'frequency_bucket'], name='question_co_company_5ae57c_idx'), models.Index(fields=['company', 'frequency_bucket', 'frequency_percentage'], name='question_co_company_1ee344_idx')],
                'constraints': [models.UniqueConstraint(fields=('question', 'company', 'frequency_bucket'), name='unique_question_company_frequency')],
            },
        ),
    ]

# Refactor: Enhance component rendering performance.

# Refactor: Improve error handling and exception logging.

# Refactor: Align with project code quality guidelines.

# Refactor: Update validation checks and constraints.

# Refactor: Update validation checks and constraints.
