# Generated by Django 5.1.15 on 2026-05-24 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0005_assessmentinvitation_instructions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('violation_count', models.IntegerField(default=0)),
                ('warning_count', models.IntegerField(default=0)),
                ('is_camera_active', models.BooleanField(default=False)),
                ('is_mic_active', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('warned', 'Warned'), ('suspended', 'Suspended'), ('completed', 'Completed'), ('auto_submitted', 'Auto-Submitted')], default='active', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Browser info, screen resolution, user agent, etc.')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_sessions', to=settings.AUTH_USER_MODEL)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_sessions', to='assessments.assessmentinvitation')),
            ],
            options={
                'db_table': 'proctoring_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProctoringLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('tab_focus_lost', 'Tab Focus Lost'), ('copy_paste', 'Copy‑Paste Detected'), ('device_change', 'Device Source Changed'), ('idle_timeout', 'Idle Timeout'), ('window_blur', 'Window Blur'), ('window_minimize', 'Window Minimize'), ('screen_change', 'Screen Change'), ('copy_attempt', 'Copy Attempt'), ('paste_attempt', 'Paste Attempt'), ('right_click', 'Right Click Blocked'), ('fullscreen_exit', 'Fullscreen Exit'), ('camera_blocked', 'Camera Access Blocked'), ('mic_blocked', 'Microphone Access Blocked'), ('warning_issued', 'Warning Issued'), ('auto_submit', 'Auto Submit Triggered')], max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event data such as viewport size, keystroke count, paste length, etc.')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_events', to='assessments.submission')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='proctoring.proctoringsession')),
            ],
            options={
                'db_table': 'proctoring_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProctoringViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('tab_switch', 'Tab Switch'), ('window_blur', 'Window Blur'), ('window_minimize', 'Window Minimize'), ('screen_change', 'Screen Change'), ('copy_attempt', 'Copy Attempt'), ('paste_attempt', 'Paste Attempt'), ('right_click', 'Right Click'), ('fullscreen_exit', 'Fullscreen Exit'), ('camera_blocked', 'Camera Blocked'), ('mic_blocked', 'Microphone Blocked'), ('idle_timeout', 'Idle Timeout')], max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('warning_shown', models.BooleanField(default=False)),
                ('auto_submitted', models.BooleanField(default=False, help_text='True if this violation triggered an auto-submit.')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='proctoring.proctoringsession')),
            ],
            options={
                'db_table': 'proctoring_violations',
                'ordering': ['-timestamp'],
            },
        ),
    ]
