# Generated by Django 5.1.15 on 2026-05-24 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_email_verified_user_profile_image_auditlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_username', models.CharField(blank=True, max_length=39)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('skill_tags', models.JSONField(blank=True, default=list, help_text="e.g., ['Python', 'DSA', 'Algorithms']")),
                ('cumulative_score', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'candidate_profiles',
            },
        ),
    ]

# Refactor: Update validation checks and constraints.
