# Generated by Django 5.1.15 on 2026-05-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='submission',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Celery task identifier for execution revocation.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('cpp', 'C++'), ('java', 'Java')], default='python', max_length=16),
        ),
    ]

# Refactor: Improve error handling and exception logging.

# Refactor: Update validation checks and constraints.

# Refactor: Optimize query performance and database indexing.

# Refactor: Optimize imports and clean up code structure.

# Refactor: Add typing hints and documentation docstrings.

# Refactor: Add typing hints and documentation docstrings.
