# Generated by Django 5.1.15 on 2026-05-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_assessment_options_submission_celery_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='Problem difficulty — determines base leaderboard points.', max_length=16),
        ),
    ]

# Refactor: Fix minor edge cases in calculation functions.
