# Generated by Django 5.1.15 on 2026-05-23 16:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_add_problem_difficulty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='assessments.assessment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assessment_invitations',
                'constraints': [models.UniqueConstraint(fields=('email', 'assessment'), name='unique_email_per_assessment_invite')],
            },
        ),
    ]

# Refactor: Fix minor edge cases in calculation functions.

# Refactor: Refactor variable names for better readability.
