# Generated by Django 5.1.15 on 2026-05-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_assessmentinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentinvitation',
            name='instructions',
            field=models.TextField(blank=True, default='', help_text='Recruiter-specified instructions shown to candidates before starting.'),
        ),
        migrations.AddField(
            model_name='assessmentinvitation',
            name='invitation_message',
            field=models.TextField(blank=True, default='', help_text='Custom message from recruiter included in the invitation.'),
        ),
        migrations.AddField(
            model_name='assessmentinvitation',
            name='proctoring_required',
            field=models.BooleanField(default=True, help_text='Whether this assessment requires camera/mic proctoring.'),
        ),
        migrations.AddField(
            model_name='assessmentinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('started', 'Started'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=16),
        ),
    ]

# Refactor: Align with project code quality guidelines.
