# Generated by Django 5.1.15 on 2026-05-24 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_assessmentinvitation_instructions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField(default=0.0)),
                ('section_scores', models.JSONField(default=dict)),
                ('mcq_accuracy', models.FloatField(default=0.0)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('proctoring_violations_count', models.PositiveIntegerField(default=0)),
                ('plagiarism_score', models.FloatField(default=0.0)),
                ('passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'assessment_reports',
            },
        ),
        migrations.CreateModel(
            name='FIBRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptable_answer', models.CharField(max_length=255)),
                ('case_sensitive', models.BooleanField(default=False)),
                ('use_regex', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'fib_rules',
            },
        ),
        migrations.CreateModel(
            name='MCQOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'mcq_options',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='pass_threshold_percentage',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='problem',
            name='question_type',
            field=models.CharField(choices=[('coding', 'Coding'), ('mcq', 'MCQ'), ('fib', 'Fill in the Blank')], default='coding', max_length=32),
        ),
        migrations.AddField(
            model_name='submission',
            name='selected_options',
            field=models.JSONField(blank=True, help_text='List of option IDs selected for MCQ', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_text',
            field=models.TextField(blank=True, help_text='Submitted text for Fill in the Blank', null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('active', 'Active'), ('archived', 'Archived'), ('expired', 'Expired')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='problem',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='assessments.assessment'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='couchdb_test_cases_doc_id',
            field=models.CharField(blank=True, help_text='CouchDB document id for hidden test cases (unstructured).', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='language',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('cpp', 'C++'), ('java', 'Java')], default='python', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='memory_limit_mb',
            field=models.PositiveIntegerField(blank=True, default=128, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit_ms',
            field=models.PositiveIntegerField(blank=True, default=2000, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='couchdb_execution_log_doc_id',
            field=models.CharField(blank=True, help_text='CouchDB document id for append-only execution log.', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='couchdb_source_doc_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessments.problem'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('section_name', models.CharField(default='Core', max_length=100)),
                ('marks', models.PositiveIntegerField(default=100)),
                ('negative_marks', models.PositiveIntegerField(default=0)),
                ('weight', models.FloatField(default=1.0)),
                ('is_required', models.BooleanField(default=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_questions', to='assessments.assessment')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_questions', to='assessments.problem')),
            ],
            options={
                'db_table': 'assessment_questions',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='assessment_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessments.assessmentquestion'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['assessment_question', 'candidate'], name='submissions_assessm_34b9ba_idx'),
        ),
        migrations.AddField(
            model_name='assessmentreport',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='assessmentreport',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentreport',
            name='invitation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='assessments.assessmentinvitation'),
        ),
        migrations.AddField(
            model_name='fibrule',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fib_rules', to='assessments.problem'),
        ),
        migrations.AddField(
            model_name='mcqoption',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_options', to='assessments.problem'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestion',
            constraint=models.UniqueConstraint(fields=('assessment', 'problem'), name='unique_assessment_problem'),
        ),
    ]

# Refactor: Fix minor edge cases in calculation functions.

# Refactor: Update validation checks and constraints.

# Refactor: Add typing hints and documentation docstrings.

# Refactor: Enhance component rendering performance.

# Refactor: Update validation checks and constraints.
