# Generated by Django 5.1.15 on 2026-05-25 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_assessmentreport_fibrule_mcqoption_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.TextField(blank=True, default='')),
                ('selected_options', models.JSONField(blank=True, default=list)),
                ('submitted_text', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_drafts', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_drafts', to='assessments.problem')),
            ],
            options={
                'db_table': 'submission_drafts',
                'unique_together': {('candidate', 'problem')},
            },
        ),
    ]
